/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package my.chatapp;

import java.util.Random;

public class Message {
    // REQUIREMENT: Unique Message ID for tracking - randomly generated ten-digit number
    private String messageID;
    
    // REQUIREMENT: Recipient - cell number with international code
    private String recipient;
    
    // REQUIREMENT: Message - should not exceed 250 characters
    private String message;
    
    // REQUIREMENT: Message Hash - autogenerated with specific format
    private String messageHash;
    
    // REQUIREMENT: Message number (from loop counter)
    private int messageNumber;
    
    // Track message status
    private boolean sent;
    private boolean stored;
    
    // Constructor
    public Message(String recipient, String message, int messageNumber) {
        this.recipient = recipient;
        this.message = message;
        this.messageNumber = messageNumber;
        this.messageID = generateMessageID();
        this.messageHash = createMessageHash();
        this.sent = false;
        this.stored = false;
    }
    
    // REQUIREMENT: Boolean checkMessageID() - ensures ID not more than ten characters
    public boolean checkMessageID() {
        return messageID != null && messageID.length() <= 10;
    }
    
    // REQUIREMENT: Int checkRecipientCell() - ensures number has no more than ten characters and contains international code
    public int checkRecipientCell() {
        if (recipient == null || recipient.isEmpty()) {
            return -1; // Invalid
        }
        
        // Remove any spaces or special characters except +
        String cleanNumber = recipient.replaceAll("[^0-9+]", "");
        
        // Check South African format: +27 followed by 9 digits (11 total)
        if (cleanNumber.matches("^\\+27[1-9]\\d{8}$")) {
            return 1; // Valid
        }
        // Check 10-digit format (without +)
        else if (cleanNumber.matches("^[1-9]\\d{9}$")) {
            return 1; // Valid
        }
        // Check if it starts with international code but might have spaces
        else if (cleanNumber.replace("+", "").matches("^27[1-9]\\d{8}$")) {
            return 1; // Valid
        }
        
        return -1; // Invalid
    }
    
    // REQUIREMENT: String createMessageHash() - creates and returns Message Hash
    public String createMessageHash() {
        // Format: first two numbers of message ID + colon + message number + colon + first and last words
        String firstTwoID = messageID.length() >= 2 ? messageID.substring(0, 2) : messageID;
        
        // Get first and last words from message
        String[] words = message.split("\\s+");
        String firstWord = words.length > 0 ? words[0].toUpperCase() : "";
        String lastWord = words.length > 1 ? words[words.length - 1].toUpperCase() : firstWord;
        
        // REQUIREMENT: Hash format: 00:0-HITHANKS (all caps)
        return firstTwoID + ":" + messageNumber + "-" + firstWord + lastWord;
    }
    
    // Generate random 10-digit message ID
    private String generateMessageID() {
        Random rand = new Random();
        StringBuilder id = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            id.append(rand.nextInt(10)); // Random digit 0-9
        }
        return id.toString();
    }
    
    // REQUIREMENT: Check if message exceeds 250 characters
    public boolean isMessageTooLong() {
        return message.length() > 250;
    }
    
    // REQUIREMENT: Get error message for long messages
    public String getLengthErrorMessage() {
        if (!isMessageTooLong()) {
            return "Message ready to send.";
        } else {
            int excess = message.length() - 250;
            return "Message exceeds 250 characters by " + excess + ", please reduce size.";
        }
    }
    
    // Getters
    public String getMessageID() { 
        return messageID; 
    }
    
    public String getRecipient() { 
        return recipient; 
    }
    
    public String getMessage() { 
        return message; 
    }
    
    public String getMessageHash() { 
        return messageHash; 
    }
    
    public int getMessageNumber() { 
        return messageNumber; 
    }
    
    public boolean isSent() { 
        return sent; 
    }
    
    public boolean isStored() { 
        return stored; 
    }
    
    // Setters
    public void setSent(boolean sent) { 
        this.sent = sent; 
    }
    
    public void setStored(boolean stored) { 
        this.stored = stored; 
    }
    
    // REQUIREMENT: Display all information in correct order for JOptionPane
    @Override
    public String toString() {
        return "Message ID: " + messageID + "\n" +
               "Message Hash: " + messageHash + "\n" +
               "Recipient: " + recipient + "\n" +
               "Message: " + message + "\n" +
               "Message Number: " + messageNumber + "\n" +
               "Status: " + (sent ? "SENT" : stored ? "STORED" : "PENDING");
    }
    
    // Method to get display format for JOptionPane (specific order from requirements)
    public String getDisplayFormat() {
        return "Message ID: " + messageID + "\n" +
               "Message Hash: " + messageHash + "\n" + 
               "Recipient: " + recipient + "\n" +
               "Message: " + message;
    }
}